# Generated by Django 4.1 on 2023-05-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('preffered', models.BooleanField()),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication', to='practitioners.practitioners')),
            ],
        ),
    ]
