# Generated by Django 4.1 on 2023-05-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('period', models.IntegerField()),
                ('issuer', models.CharField(max_length=200)),
                ('practitioners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='practitioners.practitioners')),
            ],
        ),
    ]
